site_name: VKWave
site_description: 'Документация фреймворка VKWave'
site_author: 'FSC Dev'
repo_name: 'fscdev/vkwave'
repo_url: 'https://github.com/fscdev/vkwave'

copyright: '2020-2021 FSC Dev & VkWave Contributors'

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
  font:
    code: Fira Code
  language: ru
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - instant
    - tabs
  icon:
    repo: fontawesome/brands/github

extra:
  version: 0.2.10
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/vkwave
      name: 'Чат в Telegram'

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - markdown_include.include:
      base_path: docs

nav:
  - index.md
  - Client:
      - client/index.md
      - client/context.md
      - client/using.md
      - client/custom.md
  - API:
      - api/index.md
  - Bots:
      - bots/index.md
      - bots/easy.md
      - bots/usage.md
      - bots/filters.md
      - bots/routers.md
      - bots/fsm.md
      - bots/storage.md
      - Utils:
          - bots/utils/index.md
          - bots/utils/keyboard.md
          - bots/utils/templates.md
          - bots/utils/uploaders.md
  - LongPoll:
      - longpoll/index.md
  - Types:
      - types/index.md
  - HTTP:
      - http/index.md
